package com.oddin.oddsfeedsdk.mq.entities;

public enum ProducerStatusReason {
    FIRST_RECOVERY_COMPLETED, PROCESSING_QUEUE_DELAY_STABILIZED, RETURNED_FROM_INACTIVITY, ALIVE_INTERVAL_VIOLATION, PROCESSING_QUEUE_DELAY_VIOLATION, OTHER
}
